name: Sync Repositories

on:
  workflow_dispatch:  # This allows you to trigger the action manually via GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

    - name: Set up Git for pushing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Check Secrets
      run: |
        echo "PRIVATE_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
        
    - name: Clone private repository
      run: |
        echo "Cloning private repository..."
        git clone --depth 1 --branch master https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DaGeRoot/da-cloud-commondatabase.git private-repo
        cp -r private-repo/* .  # Copy all contents from the private repository into the public repo's working directory


    - name: Add and commit changes
      run: |
        git add .
        git commit -m "Sync public repository from private repository"
        git push origin master

    - name: Clean up
      run: |
        rm -rf private-repo
